version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - ENV=local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - ENV=local
    depends_on:
      - backend
    restart: unless-stopped

  edge:
    build:
      context: ./edge
    volumes:
      - ./edge:/edge
    environment:
      - ENV=local
    depends_on:
      backend:
        condition: service_healthy
    # restart: unless-stopped
    restart: on-failure

