version: "3.9"

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - backend
    restart: always

  backend:
    build: ../backend
    container_name: backend
    expose:
      - "8000"
    volumes:
      - ../backend:/app
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
  db:
      image: mariadb:11
      container_name: mariadb
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
      ports:
        - "${DB_PORT}:3306"
      volumes:
        - db_data:/var/lib/mysql
      restart: always


volumes:
  db_data:
